config/routes.rb
Rails.application.routes.draw do
  default_url_options :host => "localhost"

  devise_for :users, :path_prefix => 'my'
  resources :users

   root 'users#welcome'
   

  resources :districts
  resources :schools do
    get :autocomplete_school_school_name, on: :collection
  end
  resources :projects do
    get :autocomplete_project_project_name, on: :collection
  end
  resources :documents

end

app/views/shared/_nav.html.erb
<!-- navbar -->
    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">DDMS</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">

            <li><%=link_to "Home", root_path %></li>
            
            <li><a href="#contact">Contact</a></li>
           
          </ul>
            <% if user_signed_in? %>
          <ul class="nav navbar-nav navbar-right">
           <% if can? :all, User %>
            <li><%=link_to "Users", users_path%></li>
            <% end %>
          <% if can? :all, District %>
            <li><%=link_to "Districts", districts_path%></li>
            <% end %>
            <li><%=link_to "Schools", schools_path%></li>
            <li><%=link_to "Projects", projects_path%></li>
            <% if can? :all, Document %>
            <li><%=link_to "Documents", documents_path%></li>
            <% end %>
            <li><%= link_to('Logout', destroy_user_session_path, :method => :delete) %></li>
            
          </ul>
          <% end %>
        </div><!--/.nav-collapse -->
      </div>
    </nav>