config/routes.rb
Rails.application.routes.draw do
  default_url_options :host => "localhost"

  devise_for :users, :path_prefix => 'my'
  resources :users

   root 'users#welcome'
   

  resources :districts
  resources :schools do
    get :autocomplete_school_school_name, on: :collection
  end
  resources :projects do
    get :autocomplete_project_project_name, on: :collection
  end
  resources :documents

end

app/models/project.rb
class Project < ActiveRecord::Base
  resourcify
  belongs_to :school
  belongs_to :district
  has_many :documents
  
  

  accepts_nested_attributes_for :district
  accepts_nested_attributes_for :school
  accepts_nested_attributes_for :documents

  validates_presence_of :project_name, :district_id, :school_id
 
 

 
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  load_and_authorize_resource :except => :autocomplete_project_project_name
  
  autocomplete :project, :project_name
  
  

  def index
    @projects = Project.accessible_by(current_ability).order(:project_name)
     if params[:search]
      
       @project = Project.find_by(project_name: params[:search])
       redirect_to project_path(@project)
       else
     end
  end



  def new
    @project = Project.new
  end
  

  def show
    @project = Project.find(params[:id])
    

  end
  def create
    @project = Project.create(project_params)
    if @project.save
      redirect_to '/projects' 
    else
      flash[:danger]="Please make sure to fill out form completely."
      #flash[:danger]=@project.errors.full_messages_for(:project_name)
      #flash[:danger]=@project.errors.full_messages_for(:district_id)
      #flash[:danger]=@project.errors.full_messages_for(:school_id)
      render 'new'
    end
  end
  def update
    

    if @project.update_attributes(project_params)
      flash[:success] = "The Project has been updated."
      redirect_to @project
    else
      flash[:danger]="Please make sure to fill out form completely."
      render 'edit'
    end
  end

  def get_autocomplete_items(parameters)
   items = active_record_get_autocomplete_items(parameters)
   items = Project.accessible_by(current_ability).select("project_name, dsa_number, id").
            where(["LOWER(project_name || ', ' ||dsa_number) " + 
                   "LIKE LOWER(?)", "%#{parameters[:term]}%"])
  end


  private
  def project_params
    params.require(:project).permit(:project_name, :project_scope, :dsa_number,:school_id, :district_id, :document_id,
                                     district_attributes:[:id, :district_name],
                                     schools_attributes:[:id, :school_name])
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<fieldset>
<%=form_for(@project, {class: "form-horizontal"}) do |f| %>
<div class="form-group pushdown">
  <%=f.text_field :project_name, placeholder: "Project Name", class: "form-control" %>
  </div>
  <div class="form-group pushdown">
  <%=f.text_field :dsa_number, placeholder: "DSA NUMBER", class: "form-control" %>
  </div>
  <div class="form-group pushdown">
  <%=f.text_area :project_scope, placeholder:"Enter scope of the project here", class: "form-control"%>
  </div>
  <div class="form-group pushdown">
<%= f.collection_select(:district_id, District.all, :id, :district_name,{include_blank: 'Select District'}, {class: "special"}) %>
</div>
  <div class="form-group pushdown">
  <%=f.grouped_collection_select(:school_id, District.order(:district_name), :schools,:district_name, :id, :school_name,  {include_blank: 'Select School'}, {class: "special"}) %>
  </div>
  <div class="form-group">
  <%=link_to "Cancel", projects_path, class: "btn btn-default buttonspace" %>

  <% if params[:action] == 'new' %>
  <%= f.submit 'Add Project', class: "btn btn-primary" %>
  <% else params[:action] == 'update' %>
  <%= f.submit 'Update Project', class: "btn btn-primary" %>
  <% end %>
  </div>
  <% end %>
  

app/views/projects/edit.html.erb
<div class="page-header pushdown"><h1>Edit Project</h1></div>
  
<%= render 'form' %>

app/views/projects/index.html.erb
<div class="container">
<div class="row pushdown">
<% if can? :all, Project %>
            <%=link_to "Add Project", new_project_path, class: "btn btn-primary" %>
            <% end %>
            </div>
<div class="row ">

<div class="form-group pushdown searchbox">
<%= form_tag(projects_path, :method => "get", id: "search-form") do %>
<%= text_field_tag :search, params[:search], class: "form-control", placeholder: "Project Search", type: "search", data: {autocomplete: autocomplete_project_project_name_projects_path}, :id_element => "#to_project_id" %> 
<%= hidden_field_tag :to_project_id, id: 'to_school_id' %>
<%= submit_tag "Search", class: "searchbutton searchbtn" %>
</div>
<div class="form-group pushdown">

<% end %>
</div>
<div class="searchinfo">
</div>
<script type="text/javascript" charset="utf-8">
  $('#search').bind('railsAutocomplete.select', function(event, data){
  $('.searchbtn').trigger('click')
  });
  </script>
</div>

            <div class="row">
<table class="table table-striped table-hover">
    <tbody>
    <tr class="pushdown">
    <th>Project Name</th>
    <th>DSA Number</th>
    <th>School</th>
    	
    </tr>
<% @projects.each do |project| %>
  
    <tr>
    <td><%= link_to project.project_name,(project) %></td>
    <td><%= project.dsa_number %></td>
    <td><%= project.school.school_name %></td>
  
    </tr>
     <% end %>
  </tbody>
  </table>
  </div>
 </div>
<%= content_for :script do %>
  new app.Projects;
<% end %>

app/views/projects/new.html.erb
<div class="page-header pushdown"><h1>Add Project</h1></div>

<%= render 'form' %>

app/views/projects/show.html.erb
<div class="container">
  <div class="row pushdown">
<% if can? :all, Project %>
            <%=link_to "Edit Project", edit_project_path(@project), class: "btn btn-primary buttonspace" %>
            <% end %>
            

            <%=link_to "Project List", projects_path, class: "btn btn-primary", 'data-no-turbolink' => true %>
            

</div>
<div class="row">
<ul class="list-group">
  <li class="list-group-item">
    <h2><%= @project.project_name %></h2><h3>DSA Number <%= @project.dsa_number %></h3>
  </li>
  <li class="list-group-item">
    <p><h5><%= @project.project_scope %></h5></p>
  </li>
  <% if can? :all, District %>
  <li class="list-group-item">
    <%= @project.district.district_name %>
  </li>
  <% end %>
  <% @project.documents.each do |document| %>
  <li class="list-group-item">
  
    <%= link_to document.document_name, document.doc.url(:original, false) %>

  </li>
  <% end %>
</ul>
</div>
</div>