config/routes.rb
Rails.application.routes.draw do
  default_url_options :host => "localhost"

  devise_for :users, :path_prefix => 'my'
  resources :users

   root 'users#welcome'
   

  resources :districts
  resources :schools do
    get :autocomplete_school_school_name, on: :collection
  end
  resources :projects do
    get :autocomplete_project_project_name, on: :collection
  end
  resources :documents

end

app/models/school.rb
class School < ActiveRecord::Base
	resourcify

	
	
	
	def access_filter
		self.accessible_by(current_ability)
	end
	

  belongs_to :district, inverse_of: :schools
  has_many :projects
  accepts_nested_attributes_for :district

  validates_presence_of :school_name, :district_id
end

app/controllers/schools_controller.rb
class SchoolsController < ApplicationController
  load_and_authorize_resource :except => :autocomplete_school_school_name
  
  autocomplete :school, :school_name
  

  
  def index
 
   @schools = School.accessible_by(current_ability).order(:school_name)
     if params[:search]
      #@school =School.name_like("%#{params[:search]}%").order('school_name')
       @school = School.find_by(school_name: params[:search])
       redirect_to school_path(@school)
       else
     end
  end
  
  def new
    @school = School.new
  end
  
  def show
    @school = School.find(params[:id])
    @district = @school.district
    @projects = @school.projects
  end
  
  def create
    @school = School.create(school_params)
    if @school.save
      redirect_to '/schools'
    else
      flash[:danger]="Please make sure to fill out form completely."
      render 'new'
    end
  end
  
  def update
    
    if @school.update_attributes(school_params)
      flash[:success] = "The School has been updated."
      redirect_to @school
    else
      flash[:danger]="Please make sure to fill out form completely."
      render 'edit'
    end
  end 
  

  def get_autocomplete_items(parameters)
   items = active_record_get_autocomplete_items(parameters)
   items = School.accessible_by(current_ability).select("school_name, id").
            where(["LOWER(school_name) " + 
                   "LIKE LOWER(?)", "%#{parameters[:term]}%"])

  end
  
  private
  def school_params
    params.require(:school).permit(:school_name, :school_location, :district_id,
                                   district_attributes:[:id, :district_name])
                                  
  end
end

app/helpers/schools_helper.rb
module SchoolsHelper
end

app/views/schools/edit.html.erb
<%=form_for(@school, {class: "form-horizontal"}) do|f| %>
<legend>Select a district then input school name:</legend>
<div class="form-group pushdown">
<%= f.collection_select(:district_id, District.all, :id, :district_name,{include_blank: 'Select District'}, {class: "special"}) %>
</div>
<div class="form-group pushdown">
  <%= f.text_field :school_name, placeholder:"Input School Name", class: "form-control" %>
  </div>
  <div class="form-group">
  <%=link_to "Cancel", schools_path, class: "btn btn-default buttonspace" %><%=f.submit "Update School", class: "btn btn-primary" %>
  <% end %>
  </div>

app/views/schools/index.html.erb
<div class="container" %>
<div class="row pushdown">
<% if can? :all, School %>
            <%=link_to "Add School", new_school_path, class: "btn btn-primary" %>
            <% end %>
</div>
<div class="row ">



<div class="form-group pushdown searchbox">
<%= form_tag(schools_path, :method => "get", id: "search-form") do %>
<%= text_field_tag :search, params[:search], class: "form-control", placeholder: "School Search", type: "search", data: {autocomplete: autocomplete_school_school_name_schools_path}, :id_element => "#to_school_id" %> 
<%= hidden_field_tag :to_school_id, id: 'to_school_id' %>
<%= submit_tag "Search", class: "searchbutton searchbtn" %>

</div>
<div class="form-group pushdown">

<% end %>
</div>
<div class="searchinfo">
</div>
<script type="text/javascript" charset="utf-8">
  $('#search').bind('railsAutocomplete.select', function(event, data){
  $('.searchbtn').trigger('click')
  });
  </script>
</div>
<div class="row">
  <table class="table table-striped table-hover">
    <tbody>
    <tr>
    <th>School</th>
    
    <th>District</th>

    </tr>

    <% @schools.each do |school| %>
    <tr>
    
    <td><%= link_to school.school_name, school_path(school) %></td>
    
    <td><%= school.district.district_name %>
</td>

    <% end %>
    </tr>
  </tbody>
  </table>
  
  </div>
</div>

app/views/schools/new.html.erb
<%=form_for(@school, {class: "form-horizontal"}) do|f| %>
<legend class="pushdown">Select a district then input school name:</legend>
<div class="form-group pushdown">
<%= f.collection_select(:district_id, District.all, :id, :district_name,{include_blank: 'Select District'}, {class: "special"}) %>
</div>
<div class="form-group pushdown">
  <%= f.text_field :school_name, placeholder:"Input School Name", class: "form-control" %>
  </div>
  <div class="form-group">
  <%=link_to "Cancel", schools_path, class: "btn btn-default buttonspace" %><%=f.submit "Add School", class: "btn btn-primary" %>
  <% end %>
  </div>

app/views/schools/show.html.erb
  <div class="row pushdown">
<% if can? :all, School %>
            <%=link_to "Edit School", edit_school_path(@school), class: "btn btn-primary pushright" %>
            <% end %>
            

            <%=link_to "School List", schools_path, class: "btn btn-primary", 'data-no-turbolink' => true  %>
            

</div>
<div class="row">
<ul class="list-group">
  <li class="list-group-item">
    <h2><%= @school.school_name %></h2>
  </li>
  <li class="list-group-item">
  <h3><%= @district.district_name %></h3>
  </li>
  <li class="list-group-item">
  <% @projects.each do |project| %>
  </li>
  <li class="list-group-item">
  
    <%= link_to project.project_name, project_path(project)%>&nbsp;&nbsp;<h6>DSA Number:&nbsp;<%= project.dsa_number %></h6>

  </li>

  <% end %>
</ul>
</div>